# moveit uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rover_arm_controller
    - rover_gripper_controller

  rover_arm_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
  rover_gripper_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - Joint_EE