# Default initial positions for legacy_pkg's ros2_control fake system

initial_positions:
  Follower_Gear_Joint: 0.0
  Joint_1: 0.0
  Joint_2: 0.0
  Joint_3: 0.0
  Joint_4: 0.0
  Joint_5: 0.0
  Left_Gripper_Joint: 0.0
  Right_Gripper_Joint: 0.0
  Servo_Gear_Joint: 0.0