# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller_controller:
  ros__parameters:
    joints:
      - Follower_Gear_Joint
      - Right_Gripper_Joint
      - Servo_Gear_Joint
      - Left_Gripper_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity