# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller_controller
    - EE_controller_controller

  arm_controller_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
    action_ns: follow_joint_trajectory
    default: true
  EE_controller_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_EE
    action_ns: follow_joint_trajectory
    default: true