# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller_controller
    - EE_controller_controller

  arm_controller_controller:
    # --- THIS WAS MISSING ---
    action_ns: follow_joint_trajectory
    default: true
    # ------------------------
    type: FollowJointTrajectory
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5

  EE_controller_controller:
    # --- THIS WAS MISSING ---
    action_ns: follow_joint_trajectory
    default: true
    # ------------------------
    type: FollowJointTrajectory
    joints:
      - Joint_EE